package icvcn

// Code generated by peg grammar.peg DO NOT EDIT.

import (
	"fmt"
	"io"
	"os"
	"sort"
	"strconv"
	"strings"
)

const endSymbol rune = 1114112

/* The rule types inferred from the grammar are below. */
type pegRule uint8

const (
	ruleUnknown pegRule = iota
	ruleVirusName
	ruleSpecies
	ruleSpeciesEpithet
	ruleMixedCaseEpithet
	ruleLowercaseEpithetNum
	ruleLowercaseEpithet
	ruleUninomial
	ruleGenus
	ruleGenusSuffix
	ruleSubfamily
	ruleSubfamilySuffix
	ruleFamily
	ruleFamilySuffix
	ruleSuborder
	ruleSuborderSuffix
	ruleOrder
	ruleOrderSuffix
	ruleSubclass
	ruleSubclassSuffix
	ruleClass
	ruleClassSuffix
	ruleSubphylum
	ruleSubphylumSuffix
	rulePhylum
	rulePhylumSuffix
	ruleSubkingdom
	ruleSubkingdomSuffix
	ruleKingdom
	ruleKingdomSuffix
	ruleSubrealm
	ruleSubrealmSuffix
	ruleRealm
	ruleRealmSuffix
	ruleDash
	ruleNum
	ruleLetter
	ruleCapsLetter
	rule_
	ruleSingleSpace
	ruleOtherSpace
	ruleEND
)

var rul3s = [...]string{
	"Unknown",
	"VirusName",
	"Species",
	"SpeciesEpithet",
	"MixedCaseEpithet",
	"LowercaseEpithetNum",
	"LowercaseEpithet",
	"Uninomial",
	"Genus",
	"GenusSuffix",
	"Subfamily",
	"SubfamilySuffix",
	"Family",
	"FamilySuffix",
	"Suborder",
	"SuborderSuffix",
	"Order",
	"OrderSuffix",
	"Subclass",
	"SubclassSuffix",
	"Class",
	"ClassSuffix",
	"Subphylum",
	"SubphylumSuffix",
	"Phylum",
	"PhylumSuffix",
	"Subkingdom",
	"SubkingdomSuffix",
	"Kingdom",
	"KingdomSuffix",
	"Subrealm",
	"SubrealmSuffix",
	"Realm",
	"RealmSuffix",
	"Dash",
	"Num",
	"Letter",
	"CapsLetter",
	"_",
	"SingleSpace",
	"OtherSpace",
	"END",
}

type token32 struct {
	pegRule
	begin, end uint32
}

func (t *token32) String() string {
	return fmt.Sprintf("\x1B[34m%v\x1B[m %v %v", rul3s[t.pegRule], t.begin, t.end)
}

type node32 struct {
	token32
	up, next *node32
}

func (node *node32) print(w io.Writer, pretty bool, buffer string) {
	var print func(node *node32, depth int)
	print = func(node *node32, depth int) {
		for node != nil {
			for c := 0; c < depth; c++ {
				fmt.Fprintf(w, " ")
			}
			rule := rul3s[node.pegRule]
			quote := strconv.Quote(string(([]rune(buffer)[node.begin:node.end])))
			if !pretty {
				fmt.Fprintf(w, "%v %v\n", rule, quote)
			} else {
				fmt.Fprintf(w, "\x1B[36m%v\x1B[m %v\n", rule, quote)
			}
			if node.up != nil {
				print(node.up, depth+1)
			}
			node = node.next
		}
	}
	print(node, 0)
}

func (node *node32) Print(w io.Writer, buffer string) {
	node.print(w, false, buffer)
}

func (node *node32) PrettyPrint(w io.Writer, buffer string) {
	node.print(w, true, buffer)
}

type tokens32 struct {
	tree []token32
}

func (t *tokens32) Trim(length uint32) {
	t.tree = t.tree[:length]
}

func (t *tokens32) Print() {
	for _, token := range t.tree {
		fmt.Println(token.String())
	}
}

func (t *tokens32) AST() *node32 {
	type element struct {
		node *node32
		down *element
	}
	tokens := t.Tokens()
	var stack *element
	for _, token := range tokens {
		if token.begin == token.end {
			continue
		}
		node := &node32{token32: token}
		for stack != nil && stack.node.begin >= token.begin && stack.node.end <= token.end {
			stack.node.next = node.up
			node.up = stack.node
			stack = stack.down
		}
		stack = &element{node: node, down: stack}
	}
	if stack != nil {
		return stack.node
	}
	return nil
}

func (t *tokens32) PrintSyntaxTree(buffer string) {
	t.AST().Print(os.Stdout, buffer)
}

func (t *tokens32) WriteSyntaxTree(w io.Writer, buffer string) {
	t.AST().Print(w, buffer)
}

func (t *tokens32) PrettyPrintSyntaxTree(buffer string) {
	t.AST().PrettyPrint(os.Stdout, buffer)
}

func (t *tokens32) Add(rule pegRule, begin, end, index uint32) {
	tree, i := t.tree, int(index)
	if i >= len(tree) {
		t.tree = append(tree, token32{pegRule: rule, begin: begin, end: end})
		return
	}
	tree[i] = token32{pegRule: rule, begin: begin, end: end}
}

func (t *tokens32) Tokens() []token32 {
	return t.tree
}

type Parser struct {
	Buffer string
	buffer []rune
	rules  [42]func() bool
	parse  func(rule ...int) error
	reset  func()
	Pretty bool
	tokens32
}

func (p *Parser) Parse(rule ...int) error {
	return p.parse(rule...)
}

func (p *Parser) Reset() {
	p.reset()
}

type textPosition struct {
	line, symbol int
}

type textPositionMap map[int]textPosition

func translatePositions(buffer []rune, positions []int) textPositionMap {
	length, translations, j, line, symbol := len(positions), make(textPositionMap, len(positions)), 0, 1, 0
	sort.Ints(positions)

search:
	for i, c := range buffer {
		if c == '\n' {
			line, symbol = line+1, 0
		} else {
			symbol++
		}
		if i == positions[j] {
			translations[positions[j]] = textPosition{line, symbol}
			for j++; j < length; j++ {
				if i != positions[j] {
					continue search
				}
			}
			break search
		}
	}

	return translations
}

type parseError struct {
	p   *Parser
	max token32
}

func (e *parseError) Error() string {
	tokens, err := []token32{e.max}, "\n"
	positions, p := make([]int, 2*len(tokens)), 0
	for _, token := range tokens {
		positions[p], p = int(token.begin), p+1
		positions[p], p = int(token.end), p+1
	}
	translations := translatePositions(e.p.buffer, positions)
	format := "parse error near %v (line %v symbol %v - line %v symbol %v):\n%v\n"
	if e.p.Pretty {
		format = "parse error near \x1B[34m%v\x1B[m (line %v symbol %v - line %v symbol %v):\n%v\n"
	}
	for _, token := range tokens {
		begin, end := int(token.begin), int(token.end)
		err += fmt.Sprintf(format,
			rul3s[token.pegRule],
			translations[begin].line, translations[begin].symbol,
			translations[end].line, translations[end].symbol,
			strconv.Quote(string(e.p.buffer[begin:end])))
	}

	return err
}

func (p *Parser) PrintSyntaxTree() {
	if p.Pretty {
		p.tokens32.PrettyPrintSyntaxTree(p.Buffer)
	} else {
		p.tokens32.PrintSyntaxTree(p.Buffer)
	}
}

func (p *Parser) WriteSyntaxTree(w io.Writer) {
	p.tokens32.WriteSyntaxTree(w, p.Buffer)
}

func (p *Parser) SprintSyntaxTree() string {
	var bldr strings.Builder
	p.WriteSyntaxTree(&bldr)
	return bldr.String()
}

func Pretty(pretty bool) func(*Parser) error {
	return func(p *Parser) error {
		p.Pretty = pretty
		return nil
	}
}

func Size(size int) func(*Parser) error {
	return func(p *Parser) error {
		p.tokens32 = tokens32{tree: make([]token32, 0, size)}
		return nil
	}
}
func (p *Parser) Init(options ...func(*Parser) error) error {
	var (
		max                  token32
		position, tokenIndex uint32
		buffer               []rune
	)
	for _, option := range options {
		err := option(p)
		if err != nil {
			return err
		}
	}
	p.reset = func() {
		max = token32{}
		position, tokenIndex = 0, 0

		p.buffer = []rune(p.Buffer)
		if len(p.buffer) == 0 || p.buffer[len(p.buffer)-1] != endSymbol {
			p.buffer = append(p.buffer, endSymbol)
		}
		buffer = p.buffer
	}
	p.reset()

	_rules := p.rules
	tree := p.tokens32
	p.parse = func(rule ...int) error {
		r := 1
		if len(rule) > 0 {
			r = rule[0]
		}
		matches := p.rules[r]()
		p.tokens32 = tree
		if matches {
			p.Trim(tokenIndex)
			return nil
		}
		return &parseError{p, max}
	}

	add := func(rule pegRule, begin uint32) {
		tree.Add(rule, begin, position, tokenIndex)
		tokenIndex++
		if begin != position && position > max.end {
			max = token32{rule, begin, position}
		}
	}

	matchDot := func() bool {
		if buffer[position] != endSymbol {
			position++
			return true
		}
		return false
	}

	/*matchChar := func(c byte) bool {
		if buffer[position] == c {
			position++
			return true
		}
		return false
	}*/

	/*matchRange := func(lower byte, upper byte) bool {
		if c := buffer[position]; c >= lower && c <= upper {
			position++
			return true
		}
		return false
	}*/

	_rules = [...]func() bool{
		nil,
		/* 0 VirusName <- <((Species / Uninomial) _? END)> */
		func() bool {
			position0, tokenIndex0 := position, tokenIndex
			{
				position1 := position
				{
					position2, tokenIndex2 := position, tokenIndex
					if !_rules[ruleSpecies]() {
						goto l3
					}
					goto l2
				l3:
					position, tokenIndex = position2, tokenIndex2
					if !_rules[ruleUninomial]() {
						goto l0
					}
				}
			l2:
				{
					position4, tokenIndex4 := position, tokenIndex
					if !_rules[rule_]() {
						goto l4
					}
					goto l5
				l4:
					position, tokenIndex = position4, tokenIndex4
				}
			l5:
				if !_rules[ruleEND]() {
					goto l0
				}
				add(ruleVirusName, position1)
			}
			return true
		l0:
			position, tokenIndex = position0, tokenIndex0
			return false
		},
		/* 1 Species <- <(Genus _ SpeciesEpithet)> */
		func() bool {
			position6, tokenIndex6 := position, tokenIndex
			{
				position7 := position
				if !_rules[ruleGenus]() {
					goto l6
				}
				if !_rules[rule_]() {
					goto l6
				}
				if !_rules[ruleSpeciesEpithet]() {
					goto l6
				}
				add(ruleSpecies, position7)
			}
			return true
		l6:
			position, tokenIndex = position6, tokenIndex6
			return false
		},
		/* 2 SpeciesEpithet <- <(MixedCaseEpithet / LowercaseEpithetNum / LowercaseEpithet)> */
		func() bool {
			position8, tokenIndex8 := position, tokenIndex
			{
				position9 := position
				{
					position10, tokenIndex10 := position, tokenIndex
					if !_rules[ruleMixedCaseEpithet]() {
						goto l11
					}
					goto l10
				l11:
					position, tokenIndex = position10, tokenIndex10
					if !_rules[ruleLowercaseEpithetNum]() {
						goto l12
					}
					goto l10
				l12:
					position, tokenIndex = position10, tokenIndex10
					if !_rules[ruleLowercaseEpithet]() {
						goto l8
					}
				}
			l10:
				add(ruleSpeciesEpithet, position9)
			}
			return true
		l8:
			position, tokenIndex = position8, tokenIndex8
			return false
		},
		/* 3 MixedCaseEpithet <- <(CapsLetter / Letter / Num / Dash)+> */
		func() bool {
			position13, tokenIndex13 := position, tokenIndex
			{
				position14 := position
				{
					position17, tokenIndex17 := position, tokenIndex
					if !_rules[ruleCapsLetter]() {
						goto l18
					}
					goto l17
				l18:
					position, tokenIndex = position17, tokenIndex17
					if !_rules[ruleLetter]() {
						goto l19
					}
					goto l17
				l19:
					position, tokenIndex = position17, tokenIndex17
					if !_rules[ruleNum]() {
						goto l20
					}
					goto l17
				l20:
					position, tokenIndex = position17, tokenIndex17
					if !_rules[ruleDash]() {
						goto l13
					}
				}
			l17:
			l15:
				{
					position16, tokenIndex16 := position, tokenIndex
					{
						position21, tokenIndex21 := position, tokenIndex
						if !_rules[ruleCapsLetter]() {
							goto l22
						}
						goto l21
					l22:
						position, tokenIndex = position21, tokenIndex21
						if !_rules[ruleLetter]() {
							goto l23
						}
						goto l21
					l23:
						position, tokenIndex = position21, tokenIndex21
						if !_rules[ruleNum]() {
							goto l24
						}
						goto l21
					l24:
						position, tokenIndex = position21, tokenIndex21
						if !_rules[ruleDash]() {
							goto l16
						}
					}
				l21:
					goto l15
				l16:
					position, tokenIndex = position16, tokenIndex16
				}
				add(ruleMixedCaseEpithet, position14)
			}
			return true
		l13:
			position, tokenIndex = position13, tokenIndex13
			return false
		},
		/* 4 LowercaseEpithetNum <- <(LowercaseEpithet Num)> */
		func() bool {
			position25, tokenIndex25 := position, tokenIndex
			{
				position26 := position
				if !_rules[ruleLowercaseEpithet]() {
					goto l25
				}
				if !_rules[ruleNum]() {
					goto l25
				}
				add(ruleLowercaseEpithetNum, position26)
			}
			return true
		l25:
			position, tokenIndex = position25, tokenIndex25
			return false
		},
		/* 5 LowercaseEpithet <- <(Letter+ (Dash? Letter+)*)> */
		func() bool {
			position27, tokenIndex27 := position, tokenIndex
			{
				position28 := position
				if !_rules[ruleLetter]() {
					goto l27
				}
			l29:
				{
					position30, tokenIndex30 := position, tokenIndex
					if !_rules[ruleLetter]() {
						goto l30
					}
					goto l29
				l30:
					position, tokenIndex = position30, tokenIndex30
				}
			l31:
				{
					position32, tokenIndex32 := position, tokenIndex
					{
						position33, tokenIndex33 := position, tokenIndex
						if !_rules[ruleDash]() {
							goto l33
						}
						goto l34
					l33:
						position, tokenIndex = position33, tokenIndex33
					}
				l34:
					if !_rules[ruleLetter]() {
						goto l32
					}
				l35:
					{
						position36, tokenIndex36 := position, tokenIndex
						if !_rules[ruleLetter]() {
							goto l36
						}
						goto l35
					l36:
						position, tokenIndex = position36, tokenIndex36
					}
					goto l31
				l32:
					position, tokenIndex = position32, tokenIndex32
				}
				add(ruleLowercaseEpithet, position28)
			}
			return true
		l27:
			position, tokenIndex = position27, tokenIndex27
			return false
		},
		/* 6 Uninomial <- <(Genus / Subfamily / Family / Suborder / Order / Subclass / Class / Subphylum / Phylum / Subkingdom / Kingdom / Subrealm / Realm)> */
		func() bool {
			position37, tokenIndex37 := position, tokenIndex
			{
				position38 := position
				{
					position39, tokenIndex39 := position, tokenIndex
					if !_rules[ruleGenus]() {
						goto l40
					}
					goto l39
				l40:
					position, tokenIndex = position39, tokenIndex39
					if !_rules[ruleSubfamily]() {
						goto l41
					}
					goto l39
				l41:
					position, tokenIndex = position39, tokenIndex39
					if !_rules[ruleFamily]() {
						goto l42
					}
					goto l39
				l42:
					position, tokenIndex = position39, tokenIndex39
					if !_rules[ruleSuborder]() {
						goto l43
					}
					goto l39
				l43:
					position, tokenIndex = position39, tokenIndex39
					if !_rules[ruleOrder]() {
						goto l44
					}
					goto l39
				l44:
					position, tokenIndex = position39, tokenIndex39
					if !_rules[ruleSubclass]() {
						goto l45
					}
					goto l39
				l45:
					position, tokenIndex = position39, tokenIndex39
					if !_rules[ruleClass]() {
						goto l46
					}
					goto l39
				l46:
					position, tokenIndex = position39, tokenIndex39
					if !_rules[ruleSubphylum]() {
						goto l47
					}
					goto l39
				l47:
					position, tokenIndex = position39, tokenIndex39
					if !_rules[rulePhylum]() {
						goto l48
					}
					goto l39
				l48:
					position, tokenIndex = position39, tokenIndex39
					if !_rules[ruleSubkingdom]() {
						goto l49
					}
					goto l39
				l49:
					position, tokenIndex = position39, tokenIndex39
					if !_rules[ruleKingdom]() {
						goto l50
					}
					goto l39
				l50:
					position, tokenIndex = position39, tokenIndex39
					if !_rules[ruleSubrealm]() {
						goto l51
					}
					goto l39
				l51:
					position, tokenIndex = position39, tokenIndex39
					if !_rules[ruleRealm]() {
						goto l37
					}
				}
			l39:
				add(ruleUninomial, position38)
			}
			return true
		l37:
			position, tokenIndex = position37, tokenIndex37
			return false
		},
		/* 7 Genus <- <(CapsLetter (!GenusSuffix Letter)+ GenusSuffix)> */
		func() bool {
			position52, tokenIndex52 := position, tokenIndex
			{
				position53 := position
				if !_rules[ruleCapsLetter]() {
					goto l52
				}
				{
					position56, tokenIndex56 := position, tokenIndex
					if !_rules[ruleGenusSuffix]() {
						goto l56
					}
					goto l52
				l56:
					position, tokenIndex = position56, tokenIndex56
				}
				if !_rules[ruleLetter]() {
					goto l52
				}
			l54:
				{
					position55, tokenIndex55 := position, tokenIndex
					{
						position57, tokenIndex57 := position, tokenIndex
						if !_rules[ruleGenusSuffix]() {
							goto l57
						}
						goto l55
					l57:
						position, tokenIndex = position57, tokenIndex57
					}
					if !_rules[ruleLetter]() {
						goto l55
					}
					goto l54
				l55:
					position, tokenIndex = position55, tokenIndex55
				}
				if !_rules[ruleGenusSuffix]() {
					goto l52
				}
				add(ruleGenus, position53)
			}
			return true
		l52:
			position, tokenIndex = position52, tokenIndex52
			return false
		},
		/* 8 GenusSuffix <- <((('v' 'i' 'r' 'u' 's') / ('v' 'i' 'r' 'o' 'i' 'd') / ('s' 'a' 't' 'e' 'l' 'l' 'i' 't' 'e') / ('v' 'i' 'r' 'i' 'f' 'o' 'r' 'm')) !Letter)> */
		func() bool {
			position58, tokenIndex58 := position, tokenIndex
			{
				position59 := position
				{
					position60, tokenIndex60 := position, tokenIndex
					if buffer[position] != rune('v') {
						goto l61
					}
					position++
					if buffer[position] != rune('i') {
						goto l61
					}
					position++
					if buffer[position] != rune('r') {
						goto l61
					}
					position++
					if buffer[position] != rune('u') {
						goto l61
					}
					position++
					if buffer[position] != rune('s') {
						goto l61
					}
					position++
					goto l60
				l61:
					position, tokenIndex = position60, tokenIndex60
					if buffer[position] != rune('v') {
						goto l62
					}
					position++
					if buffer[position] != rune('i') {
						goto l62
					}
					position++
					if buffer[position] != rune('r') {
						goto l62
					}
					position++
					if buffer[position] != rune('o') {
						goto l62
					}
					position++
					if buffer[position] != rune('i') {
						goto l62
					}
					position++
					if buffer[position] != rune('d') {
						goto l62
					}
					position++
					goto l60
				l62:
					position, tokenIndex = position60, tokenIndex60
					if buffer[position] != rune('s') {
						goto l63
					}
					position++
					if buffer[position] != rune('a') {
						goto l63
					}
					position++
					if buffer[position] != rune('t') {
						goto l63
					}
					position++
					if buffer[position] != rune('e') {
						goto l63
					}
					position++
					if buffer[position] != rune('l') {
						goto l63
					}
					position++
					if buffer[position] != rune('l') {
						goto l63
					}
					position++
					if buffer[position] != rune('i') {
						goto l63
					}
					position++
					if buffer[position] != rune('t') {
						goto l63
					}
					position++
					if buffer[position] != rune('e') {
						goto l63
					}
					position++
					goto l60
				l63:
					position, tokenIndex = position60, tokenIndex60
					if buffer[position] != rune('v') {
						goto l58
					}
					position++
					if buffer[position] != rune('i') {
						goto l58
					}
					position++
					if buffer[position] != rune('r') {
						goto l58
					}
					position++
					if buffer[position] != rune('i') {
						goto l58
					}
					position++
					if buffer[position] != rune('f') {
						goto l58
					}
					position++
					if buffer[position] != rune('o') {
						goto l58
					}
					position++
					if buffer[position] != rune('r') {
						goto l58
					}
					position++
					if buffer[position] != rune('m') {
						goto l58
					}
					position++
				}
			l60:
				{
					position64, tokenIndex64 := position, tokenIndex
					if !_rules[ruleLetter]() {
						goto l64
					}
					goto l58
				l64:
					position, tokenIndex = position64, tokenIndex64
				}
				add(ruleGenusSuffix, position59)
			}
			return true
		l58:
			position, tokenIndex = position58, tokenIndex58
			return false
		},
		/* 9 Subfamily <- <(CapsLetter (!SubfamilySuffix Letter)+ SubfamilySuffix)> */
		func() bool {
			position65, tokenIndex65 := position, tokenIndex
			{
				position66 := position
				if !_rules[ruleCapsLetter]() {
					goto l65
				}
				{
					position69, tokenIndex69 := position, tokenIndex
					if !_rules[ruleSubfamilySuffix]() {
						goto l69
					}
					goto l65
				l69:
					position, tokenIndex = position69, tokenIndex69
				}
				if !_rules[ruleLetter]() {
					goto l65
				}
			l67:
				{
					position68, tokenIndex68 := position, tokenIndex
					{
						position70, tokenIndex70 := position, tokenIndex
						if !_rules[ruleSubfamilySuffix]() {
							goto l70
						}
						goto l68
					l70:
						position, tokenIndex = position70, tokenIndex70
					}
					if !_rules[ruleLetter]() {
						goto l68
					}
					goto l67
				l68:
					position, tokenIndex = position68, tokenIndex68
				}
				if !_rules[ruleSubfamilySuffix]() {
					goto l65
				}
				add(ruleSubfamily, position66)
			}
			return true
		l65:
			position, tokenIndex = position65, tokenIndex65
			return false
		},
		/* 10 SubfamilySuffix <- <((('v' 'i' 'r' 'i' 'n' 'a' 'e') / ('v' 'i' 'r' 'o' 'i' 'd' 'i' 'n' 'a' 'e') / ('s' 'a' 't' 'e' 'l' 'l' 'i' 't' 'i' 'n' 'a' 'e') / ('v' 'i' 'r' 'i' 'f' 'o' 'r' 'm' 'i' 'n' 'a' 'e')) !Letter)> */
		func() bool {
			position71, tokenIndex71 := position, tokenIndex
			{
				position72 := position
				{
					position73, tokenIndex73 := position, tokenIndex
					if buffer[position] != rune('v') {
						goto l74
					}
					position++
					if buffer[position] != rune('i') {
						goto l74
					}
					position++
					if buffer[position] != rune('r') {
						goto l74
					}
					position++
					if buffer[position] != rune('i') {
						goto l74
					}
					position++
					if buffer[position] != rune('n') {
						goto l74
					}
					position++
					if buffer[position] != rune('a') {
						goto l74
					}
					position++
					if buffer[position] != rune('e') {
						goto l74
					}
					position++
					goto l73
				l74:
					position, tokenIndex = position73, tokenIndex73
					if buffer[position] != rune('v') {
						goto l75
					}
					position++
					if buffer[position] != rune('i') {
						goto l75
					}
					position++
					if buffer[position] != rune('r') {
						goto l75
					}
					position++
					if buffer[position] != rune('o') {
						goto l75
					}
					position++
					if buffer[position] != rune('i') {
						goto l75
					}
					position++
					if buffer[position] != rune('d') {
						goto l75
					}
					position++
					if buffer[position] != rune('i') {
						goto l75
					}
					position++
					if buffer[position] != rune('n') {
						goto l75
					}
					position++
					if buffer[position] != rune('a') {
						goto l75
					}
					position++
					if buffer[position] != rune('e') {
						goto l75
					}
					position++
					goto l73
				l75:
					position, tokenIndex = position73, tokenIndex73
					if buffer[position] != rune('s') {
						goto l76
					}
					position++
					if buffer[position] != rune('a') {
						goto l76
					}
					position++
					if buffer[position] != rune('t') {
						goto l76
					}
					position++
					if buffer[position] != rune('e') {
						goto l76
					}
					position++
					if buffer[position] != rune('l') {
						goto l76
					}
					position++
					if buffer[position] != rune('l') {
						goto l76
					}
					position++
					if buffer[position] != rune('i') {
						goto l76
					}
					position++
					if buffer[position] != rune('t') {
						goto l76
					}
					position++
					if buffer[position] != rune('i') {
						goto l76
					}
					position++
					if buffer[position] != rune('n') {
						goto l76
					}
					position++
					if buffer[position] != rune('a') {
						goto l76
					}
					position++
					if buffer[position] != rune('e') {
						goto l76
					}
					position++
					goto l73
				l76:
					position, tokenIndex = position73, tokenIndex73
					if buffer[position] != rune('v') {
						goto l71
					}
					position++
					if buffer[position] != rune('i') {
						goto l71
					}
					position++
					if buffer[position] != rune('r') {
						goto l71
					}
					position++
					if buffer[position] != rune('i') {
						goto l71
					}
					position++
					if buffer[position] != rune('f') {
						goto l71
					}
					position++
					if buffer[position] != rune('o') {
						goto l71
					}
					position++
					if buffer[position] != rune('r') {
						goto l71
					}
					position++
					if buffer[position] != rune('m') {
						goto l71
					}
					position++
					if buffer[position] != rune('i') {
						goto l71
					}
					position++
					if buffer[position] != rune('n') {
						goto l71
					}
					position++
					if buffer[position] != rune('a') {
						goto l71
					}
					position++
					if buffer[position] != rune('e') {
						goto l71
					}
					position++
				}
			l73:
				{
					position77, tokenIndex77 := position, tokenIndex
					if !_rules[ruleLetter]() {
						goto l77
					}
					goto l71
				l77:
					position, tokenIndex = position77, tokenIndex77
				}
				add(ruleSubfamilySuffix, position72)
			}
			return true
		l71:
			position, tokenIndex = position71, tokenIndex71
			return false
		},
		/* 11 Family <- <(CapsLetter (!FamilySuffix Letter)+ FamilySuffix)> */
		func() bool {
			position78, tokenIndex78 := position, tokenIndex
			{
				position79 := position
				if !_rules[ruleCapsLetter]() {
					goto l78
				}
				{
					position82, tokenIndex82 := position, tokenIndex
					if !_rules[ruleFamilySuffix]() {
						goto l82
					}
					goto l78
				l82:
					position, tokenIndex = position82, tokenIndex82
				}
				if !_rules[ruleLetter]() {
					goto l78
				}
			l80:
				{
					position81, tokenIndex81 := position, tokenIndex
					{
						position83, tokenIndex83 := position, tokenIndex
						if !_rules[ruleFamilySuffix]() {
							goto l83
						}
						goto l81
					l83:
						position, tokenIndex = position83, tokenIndex83
					}
					if !_rules[ruleLetter]() {
						goto l81
					}
					goto l80
				l81:
					position, tokenIndex = position81, tokenIndex81
				}
				if !_rules[ruleFamilySuffix]() {
					goto l78
				}
				add(ruleFamily, position79)
			}
			return true
		l78:
			position, tokenIndex = position78, tokenIndex78
			return false
		},
		/* 12 FamilySuffix <- <((('v' 'i' 'r' 'i' 'd' 'a' 'e') / ('v' 'i' 'r' 'o' 'i' 'd' 'a' 'e') / ('s' 'a' 't' 'e' 'l' 'l' 'i' 't' 'i' 'd' 'a' 'e') / ('v' 'i' 'r' 'i' 'f' 'o' 'r' 'm' 'i' 'd' 'a' 'e')) !Letter)> */
		func() bool {
			position84, tokenIndex84 := position, tokenIndex
			{
				position85 := position
				{
					position86, tokenIndex86 := position, tokenIndex
					if buffer[position] != rune('v') {
						goto l87
					}
					position++
					if buffer[position] != rune('i') {
						goto l87
					}
					position++
					if buffer[position] != rune('r') {
						goto l87
					}
					position++
					if buffer[position] != rune('i') {
						goto l87
					}
					position++
					if buffer[position] != rune('d') {
						goto l87
					}
					position++
					if buffer[position] != rune('a') {
						goto l87
					}
					position++
					if buffer[position] != rune('e') {
						goto l87
					}
					position++
					goto l86
				l87:
					position, tokenIndex = position86, tokenIndex86
					if buffer[position] != rune('v') {
						goto l88
					}
					position++
					if buffer[position] != rune('i') {
						goto l88
					}
					position++
					if buffer[position] != rune('r') {
						goto l88
					}
					position++
					if buffer[position] != rune('o') {
						goto l88
					}
					position++
					if buffer[position] != rune('i') {
						goto l88
					}
					position++
					if buffer[position] != rune('d') {
						goto l88
					}
					position++
					if buffer[position] != rune('a') {
						goto l88
					}
					position++
					if buffer[position] != rune('e') {
						goto l88
					}
					position++
					goto l86
				l88:
					position, tokenIndex = position86, tokenIndex86
					if buffer[position] != rune('s') {
						goto l89
					}
					position++
					if buffer[position] != rune('a') {
						goto l89
					}
					position++
					if buffer[position] != rune('t') {
						goto l89
					}
					position++
					if buffer[position] != rune('e') {
						goto l89
					}
					position++
					if buffer[position] != rune('l') {
						goto l89
					}
					position++
					if buffer[position] != rune('l') {
						goto l89
					}
					position++
					if buffer[position] != rune('i') {
						goto l89
					}
					position++
					if buffer[position] != rune('t') {
						goto l89
					}
					position++
					if buffer[position] != rune('i') {
						goto l89
					}
					position++
					if buffer[position] != rune('d') {
						goto l89
					}
					position++
					if buffer[position] != rune('a') {
						goto l89
					}
					position++
					if buffer[position] != rune('e') {
						goto l89
					}
					position++
					goto l86
				l89:
					position, tokenIndex = position86, tokenIndex86
					if buffer[position] != rune('v') {
						goto l84
					}
					position++
					if buffer[position] != rune('i') {
						goto l84
					}
					position++
					if buffer[position] != rune('r') {
						goto l84
					}
					position++
					if buffer[position] != rune('i') {
						goto l84
					}
					position++
					if buffer[position] != rune('f') {
						goto l84
					}
					position++
					if buffer[position] != rune('o') {
						goto l84
					}
					position++
					if buffer[position] != rune('r') {
						goto l84
					}
					position++
					if buffer[position] != rune('m') {
						goto l84
					}
					position++
					if buffer[position] != rune('i') {
						goto l84
					}
					position++
					if buffer[position] != rune('d') {
						goto l84
					}
					position++
					if buffer[position] != rune('a') {
						goto l84
					}
					position++
					if buffer[position] != rune('e') {
						goto l84
					}
					position++
				}
			l86:
				{
					position90, tokenIndex90 := position, tokenIndex
					if !_rules[ruleLetter]() {
						goto l90
					}
					goto l84
				l90:
					position, tokenIndex = position90, tokenIndex90
				}
				add(ruleFamilySuffix, position85)
			}
			return true
		l84:
			position, tokenIndex = position84, tokenIndex84
			return false
		},
		/* 13 Suborder <- <(CapsLetter (!SuborderSuffix Letter)+ SuborderSuffix)> */
		func() bool {
			position91, tokenIndex91 := position, tokenIndex
			{
				position92 := position
				if !_rules[ruleCapsLetter]() {
					goto l91
				}
				{
					position95, tokenIndex95 := position, tokenIndex
					if !_rules[ruleSuborderSuffix]() {
						goto l95
					}
					goto l91
				l95:
					position, tokenIndex = position95, tokenIndex95
				}
				if !_rules[ruleLetter]() {
					goto l91
				}
			l93:
				{
					position94, tokenIndex94 := position, tokenIndex
					{
						position96, tokenIndex96 := position, tokenIndex
						if !_rules[ruleSuborderSuffix]() {
							goto l96
						}
						goto l94
					l96:
						position, tokenIndex = position96, tokenIndex96
					}
					if !_rules[ruleLetter]() {
						goto l94
					}
					goto l93
				l94:
					position, tokenIndex = position94, tokenIndex94
				}
				if !_rules[ruleSuborderSuffix]() {
					goto l91
				}
				add(ruleSuborder, position92)
			}
			return true
		l91:
			position, tokenIndex = position91, tokenIndex91
			return false
		},
		/* 14 SuborderSuffix <- <((('v' 'i' 'r' 'i' 'n' 'e' 'a' 'e') / ('v' 'i' 'r' 'o' 'i' 'd' 'i' 'n' 'e' 'a' 'e') / ('s' 'a' 't' 'e' 'l' 'l' 'i' 't' 'i' 'n' 'e' 'a' 'e') / ('v' 'i' 'r' 'i' 'f' 'o' 'r' 'm' 'i' 'n' 'e' 'a' 'e')) !Letter)> */
		func() bool {
			position97, tokenIndex97 := position, tokenIndex
			{
				position98 := position
				{
					position99, tokenIndex99 := position, tokenIndex
					if buffer[position] != rune('v') {
						goto l100
					}
					position++
					if buffer[position] != rune('i') {
						goto l100
					}
					position++
					if buffer[position] != rune('r') {
						goto l100
					}
					position++
					if buffer[position] != rune('i') {
						goto l100
					}
					position++
					if buffer[position] != rune('n') {
						goto l100
					}
					position++
					if buffer[position] != rune('e') {
						goto l100
					}
					position++
					if buffer[position] != rune('a') {
						goto l100
					}
					position++
					if buffer[position] != rune('e') {
						goto l100
					}
					position++
					goto l99
				l100:
					position, tokenIndex = position99, tokenIndex99
					if buffer[position] != rune('v') {
						goto l101
					}
					position++
					if buffer[position] != rune('i') {
						goto l101
					}
					position++
					if buffer[position] != rune('r') {
						goto l101
					}
					position++
					if buffer[position] != rune('o') {
						goto l101
					}
					position++
					if buffer[position] != rune('i') {
						goto l101
					}
					position++
					if buffer[position] != rune('d') {
						goto l101
					}
					position++
					if buffer[position] != rune('i') {
						goto l101
					}
					position++
					if buffer[position] != rune('n') {
						goto l101
					}
					position++
					if buffer[position] != rune('e') {
						goto l101
					}
					position++
					if buffer[position] != rune('a') {
						goto l101
					}
					position++
					if buffer[position] != rune('e') {
						goto l101
					}
					position++
					goto l99
				l101:
					position, tokenIndex = position99, tokenIndex99
					if buffer[position] != rune('s') {
						goto l102
					}
					position++
					if buffer[position] != rune('a') {
						goto l102
					}
					position++
					if buffer[position] != rune('t') {
						goto l102
					}
					position++
					if buffer[position] != rune('e') {
						goto l102
					}
					position++
					if buffer[position] != rune('l') {
						goto l102
					}
					position++
					if buffer[position] != rune('l') {
						goto l102
					}
					position++
					if buffer[position] != rune('i') {
						goto l102
					}
					position++
					if buffer[position] != rune('t') {
						goto l102
					}
					position++
					if buffer[position] != rune('i') {
						goto l102
					}
					position++
					if buffer[position] != rune('n') {
						goto l102
					}
					position++
					if buffer[position] != rune('e') {
						goto l102
					}
					position++
					if buffer[position] != rune('a') {
						goto l102
					}
					position++
					if buffer[position] != rune('e') {
						goto l102
					}
					position++
					goto l99
				l102:
					position, tokenIndex = position99, tokenIndex99
					if buffer[position] != rune('v') {
						goto l97
					}
					position++
					if buffer[position] != rune('i') {
						goto l97
					}
					position++
					if buffer[position] != rune('r') {
						goto l97
					}
					position++
					if buffer[position] != rune('i') {
						goto l97
					}
					position++
					if buffer[position] != rune('f') {
						goto l97
					}
					position++
					if buffer[position] != rune('o') {
						goto l97
					}
					position++
					if buffer[position] != rune('r') {
						goto l97
					}
					position++
					if buffer[position] != rune('m') {
						goto l97
					}
					position++
					if buffer[position] != rune('i') {
						goto l97
					}
					position++
					if buffer[position] != rune('n') {
						goto l97
					}
					position++
					if buffer[position] != rune('e') {
						goto l97
					}
					position++
					if buffer[position] != rune('a') {
						goto l97
					}
					position++
					if buffer[position] != rune('e') {
						goto l97
					}
					position++
				}
			l99:
				{
					position103, tokenIndex103 := position, tokenIndex
					if !_rules[ruleLetter]() {
						goto l103
					}
					goto l97
				l103:
					position, tokenIndex = position103, tokenIndex103
				}
				add(ruleSuborderSuffix, position98)
			}
			return true
		l97:
			position, tokenIndex = position97, tokenIndex97
			return false
		},
		/* 15 Order <- <(CapsLetter (!OrderSuffix Letter)+ OrderSuffix)> */
		func() bool {
			position104, tokenIndex104 := position, tokenIndex
			{
				position105 := position
				if !_rules[ruleCapsLetter]() {
					goto l104
				}
				{
					position108, tokenIndex108 := position, tokenIndex
					if !_rules[ruleOrderSuffix]() {
						goto l108
					}
					goto l104
				l108:
					position, tokenIndex = position108, tokenIndex108
				}
				if !_rules[ruleLetter]() {
					goto l104
				}
			l106:
				{
					position107, tokenIndex107 := position, tokenIndex
					{
						position109, tokenIndex109 := position, tokenIndex
						if !_rules[ruleOrderSuffix]() {
							goto l109
						}
						goto l107
					l109:
						position, tokenIndex = position109, tokenIndex109
					}
					if !_rules[ruleLetter]() {
						goto l107
					}
					goto l106
				l107:
					position, tokenIndex = position107, tokenIndex107
				}
				if !_rules[ruleOrderSuffix]() {
					goto l104
				}
				add(ruleOrder, position105)
			}
			return true
		l104:
			position, tokenIndex = position104, tokenIndex104
			return false
		},
		/* 16 OrderSuffix <- <((('v' 'i' 'r' 'a' 'l' 'e' 's') / ('v' 'i' 'r' 'o' 'i' 'd' 'a' 'l' 'e' 's') / ('s' 'a' 't' 'e' 'l' 'l' 'i' 't' 'a' 'l' 'e' 's') / ('v' 'i' 'r' 'i' 'f' 'o' 'r' 'm' 'a' 'l' 'e' 's')) !Letter)> */
		func() bool {
			position110, tokenIndex110 := position, tokenIndex
			{
				position111 := position
				{
					position112, tokenIndex112 := position, tokenIndex
					if buffer[position] != rune('v') {
						goto l113
					}
					position++
					if buffer[position] != rune('i') {
						goto l113
					}
					position++
					if buffer[position] != rune('r') {
						goto l113
					}
					position++
					if buffer[position] != rune('a') {
						goto l113
					}
					position++
					if buffer[position] != rune('l') {
						goto l113
					}
					position++
					if buffer[position] != rune('e') {
						goto l113
					}
					position++
					if buffer[position] != rune('s') {
						goto l113
					}
					position++
					goto l112
				l113:
					position, tokenIndex = position112, tokenIndex112
					if buffer[position] != rune('v') {
						goto l114
					}
					position++
					if buffer[position] != rune('i') {
						goto l114
					}
					position++
					if buffer[position] != rune('r') {
						goto l114
					}
					position++
					if buffer[position] != rune('o') {
						goto l114
					}
					position++
					if buffer[position] != rune('i') {
						goto l114
					}
					position++
					if buffer[position] != rune('d') {
						goto l114
					}
					position++
					if buffer[position] != rune('a') {
						goto l114
					}
					position++
					if buffer[position] != rune('l') {
						goto l114
					}
					position++
					if buffer[position] != rune('e') {
						goto l114
					}
					position++
					if buffer[position] != rune('s') {
						goto l114
					}
					position++
					goto l112
				l114:
					position, tokenIndex = position112, tokenIndex112
					if buffer[position] != rune('s') {
						goto l115
					}
					position++
					if buffer[position] != rune('a') {
						goto l115
					}
					position++
					if buffer[position] != rune('t') {
						goto l115
					}
					position++
					if buffer[position] != rune('e') {
						goto l115
					}
					position++
					if buffer[position] != rune('l') {
						goto l115
					}
					position++
					if buffer[position] != rune('l') {
						goto l115
					}
					position++
					if buffer[position] != rune('i') {
						goto l115
					}
					position++
					if buffer[position] != rune('t') {
						goto l115
					}
					position++
					if buffer[position] != rune('a') {
						goto l115
					}
					position++
					if buffer[position] != rune('l') {
						goto l115
					}
					position++
					if buffer[position] != rune('e') {
						goto l115
					}
					position++
					if buffer[position] != rune('s') {
						goto l115
					}
					position++
					goto l112
				l115:
					position, tokenIndex = position112, tokenIndex112
					if buffer[position] != rune('v') {
						goto l110
					}
					position++
					if buffer[position] != rune('i') {
						goto l110
					}
					position++
					if buffer[position] != rune('r') {
						goto l110
					}
					position++
					if buffer[position] != rune('i') {
						goto l110
					}
					position++
					if buffer[position] != rune('f') {
						goto l110
					}
					position++
					if buffer[position] != rune('o') {
						goto l110
					}
					position++
					if buffer[position] != rune('r') {
						goto l110
					}
					position++
					if buffer[position] != rune('m') {
						goto l110
					}
					position++
					if buffer[position] != rune('a') {
						goto l110
					}
					position++
					if buffer[position] != rune('l') {
						goto l110
					}
					position++
					if buffer[position] != rune('e') {
						goto l110
					}
					position++
					if buffer[position] != rune('s') {
						goto l110
					}
					position++
				}
			l112:
				{
					position116, tokenIndex116 := position, tokenIndex
					if !_rules[ruleLetter]() {
						goto l116
					}
					goto l110
				l116:
					position, tokenIndex = position116, tokenIndex116
				}
				add(ruleOrderSuffix, position111)
			}
			return true
		l110:
			position, tokenIndex = position110, tokenIndex110
			return false
		},
		/* 17 Subclass <- <(CapsLetter (!SubclassSuffix Letter)+ SubclassSuffix)> */
		func() bool {
			position117, tokenIndex117 := position, tokenIndex
			{
				position118 := position
				if !_rules[ruleCapsLetter]() {
					goto l117
				}
				{
					position121, tokenIndex121 := position, tokenIndex
					if !_rules[ruleSubclassSuffix]() {
						goto l121
					}
					goto l117
				l121:
					position, tokenIndex = position121, tokenIndex121
				}
				if !_rules[ruleLetter]() {
					goto l117
				}
			l119:
				{
					position120, tokenIndex120 := position, tokenIndex
					{
						position122, tokenIndex122 := position, tokenIndex
						if !_rules[ruleSubclassSuffix]() {
							goto l122
						}
						goto l120
					l122:
						position, tokenIndex = position122, tokenIndex122
					}
					if !_rules[ruleLetter]() {
						goto l120
					}
					goto l119
				l120:
					position, tokenIndex = position120, tokenIndex120
				}
				if !_rules[ruleSubclassSuffix]() {
					goto l117
				}
				add(ruleSubclass, position118)
			}
			return true
		l117:
			position, tokenIndex = position117, tokenIndex117
			return false
		},
		/* 18 SubclassSuffix <- <((('v' 'i' 'r' 'i' 'c' 'e' 't' 'i' 'd' 'a' 'e') / ('v' 'i' 'r' 'o' 'i' 'd' 'i' 'c' 'e' 't' 'i' 'd' 'a' 'e') / ('s' 'a' 't' 'e' 'l' 'l' 'i' 't' 'i' 'c' 'e' 't' 'i' 'd' 'a' 'e') / ('v' 'i' 'r' 'i' 'f' 'o' 'r' 'm' 'i' 'c' 'e' 't' 'i' 'd' 'e' 'a')) !Letter)> */
		func() bool {
			position123, tokenIndex123 := position, tokenIndex
			{
				position124 := position
				{
					position125, tokenIndex125 := position, tokenIndex
					if buffer[position] != rune('v') {
						goto l126
					}
					position++
					if buffer[position] != rune('i') {
						goto l126
					}
					position++
					if buffer[position] != rune('r') {
						goto l126
					}
					position++
					if buffer[position] != rune('i') {
						goto l126
					}
					position++
					if buffer[position] != rune('c') {
						goto l126
					}
					position++
					if buffer[position] != rune('e') {
						goto l126
					}
					position++
					if buffer[position] != rune('t') {
						goto l126
					}
					position++
					if buffer[position] != rune('i') {
						goto l126
					}
					position++
					if buffer[position] != rune('d') {
						goto l126
					}
					position++
					if buffer[position] != rune('a') {
						goto l126
					}
					position++
					if buffer[position] != rune('e') {
						goto l126
					}
					position++
					goto l125
				l126:
					position, tokenIndex = position125, tokenIndex125
					if buffer[position] != rune('v') {
						goto l127
					}
					position++
					if buffer[position] != rune('i') {
						goto l127
					}
					position++
					if buffer[position] != rune('r') {
						goto l127
					}
					position++
					if buffer[position] != rune('o') {
						goto l127
					}
					position++
					if buffer[position] != rune('i') {
						goto l127
					}
					position++
					if buffer[position] != rune('d') {
						goto l127
					}
					position++
					if buffer[position] != rune('i') {
						goto l127
					}
					position++
					if buffer[position] != rune('c') {
						goto l127
					}
					position++
					if buffer[position] != rune('e') {
						goto l127
					}
					position++
					if buffer[position] != rune('t') {
						goto l127
					}
					position++
					if buffer[position] != rune('i') {
						goto l127
					}
					position++
					if buffer[position] != rune('d') {
						goto l127
					}
					position++
					if buffer[position] != rune('a') {
						goto l127
					}
					position++
					if buffer[position] != rune('e') {
						goto l127
					}
					position++
					goto l125
				l127:
					position, tokenIndex = position125, tokenIndex125
					if buffer[position] != rune('s') {
						goto l128
					}
					position++
					if buffer[position] != rune('a') {
						goto l128
					}
					position++
					if buffer[position] != rune('t') {
						goto l128
					}
					position++
					if buffer[position] != rune('e') {
						goto l128
					}
					position++
					if buffer[position] != rune('l') {
						goto l128
					}
					position++
					if buffer[position] != rune('l') {
						goto l128
					}
					position++
					if buffer[position] != rune('i') {
						goto l128
					}
					position++
					if buffer[position] != rune('t') {
						goto l128
					}
					position++
					if buffer[position] != rune('i') {
						goto l128
					}
					position++
					if buffer[position] != rune('c') {
						goto l128
					}
					position++
					if buffer[position] != rune('e') {
						goto l128
					}
					position++
					if buffer[position] != rune('t') {
						goto l128
					}
					position++
					if buffer[position] != rune('i') {
						goto l128
					}
					position++
					if buffer[position] != rune('d') {
						goto l128
					}
					position++
					if buffer[position] != rune('a') {
						goto l128
					}
					position++
					if buffer[position] != rune('e') {
						goto l128
					}
					position++
					goto l125
				l128:
					position, tokenIndex = position125, tokenIndex125
					if buffer[position] != rune('v') {
						goto l123
					}
					position++
					if buffer[position] != rune('i') {
						goto l123
					}
					position++
					if buffer[position] != rune('r') {
						goto l123
					}
					position++
					if buffer[position] != rune('i') {
						goto l123
					}
					position++
					if buffer[position] != rune('f') {
						goto l123
					}
					position++
					if buffer[position] != rune('o') {
						goto l123
					}
					position++
					if buffer[position] != rune('r') {
						goto l123
					}
					position++
					if buffer[position] != rune('m') {
						goto l123
					}
					position++
					if buffer[position] != rune('i') {
						goto l123
					}
					position++
					if buffer[position] != rune('c') {
						goto l123
					}
					position++
					if buffer[position] != rune('e') {
						goto l123
					}
					position++
					if buffer[position] != rune('t') {
						goto l123
					}
					position++
					if buffer[position] != rune('i') {
						goto l123
					}
					position++
					if buffer[position] != rune('d') {
						goto l123
					}
					position++
					if buffer[position] != rune('e') {
						goto l123
					}
					position++
					if buffer[position] != rune('a') {
						goto l123
					}
					position++
				}
			l125:
				{
					position129, tokenIndex129 := position, tokenIndex
					if !_rules[ruleLetter]() {
						goto l129
					}
					goto l123
				l129:
					position, tokenIndex = position129, tokenIndex129
				}
				add(ruleSubclassSuffix, position124)
			}
			return true
		l123:
			position, tokenIndex = position123, tokenIndex123
			return false
		},
		/* 19 Class <- <(CapsLetter (!ClassSuffix Letter)+ ClassSuffix)> */
		func() bool {
			position130, tokenIndex130 := position, tokenIndex
			{
				position131 := position
				if !_rules[ruleCapsLetter]() {
					goto l130
				}
				{
					position134, tokenIndex134 := position, tokenIndex
					if !_rules[ruleClassSuffix]() {
						goto l134
					}
					goto l130
				l134:
					position, tokenIndex = position134, tokenIndex134
				}
				if !_rules[ruleLetter]() {
					goto l130
				}
			l132:
				{
					position133, tokenIndex133 := position, tokenIndex
					{
						position135, tokenIndex135 := position, tokenIndex
						if !_rules[ruleClassSuffix]() {
							goto l135
						}
						goto l133
					l135:
						position, tokenIndex = position135, tokenIndex135
					}
					if !_rules[ruleLetter]() {
						goto l133
					}
					goto l132
				l133:
					position, tokenIndex = position133, tokenIndex133
				}
				if !_rules[ruleClassSuffix]() {
					goto l130
				}
				add(ruleClass, position131)
			}
			return true
		l130:
			position, tokenIndex = position130, tokenIndex130
			return false
		},
		/* 20 ClassSuffix <- <((('v' 'i' 'r' 'i' 'c' 'e' 't' 'e' 's') / ('v' 'i' 'r' 'o' 'i' 'd' 'i' 'c' 'e' 't' 'e' 's') / ('s' 'a' 't' 'e' 'l' 'l' 'i' 't' 'i' 'c' 'e' 't' 'e' 's') / ('v' 'i' 'r' 'i' 'f' 'o' 'r' 'm' 'i' 'c' 'e' 't' 'e' 's')) !Letter)> */
		func() bool {
			position136, tokenIndex136 := position, tokenIndex
			{
				position137 := position
				{
					position138, tokenIndex138 := position, tokenIndex
					if buffer[position] != rune('v') {
						goto l139
					}
					position++
					if buffer[position] != rune('i') {
						goto l139
					}
					position++
					if buffer[position] != rune('r') {
						goto l139
					}
					position++
					if buffer[position] != rune('i') {
						goto l139
					}
					position++
					if buffer[position] != rune('c') {
						goto l139
					}
					position++
					if buffer[position] != rune('e') {
						goto l139
					}
					position++
					if buffer[position] != rune('t') {
						goto l139
					}
					position++
					if buffer[position] != rune('e') {
						goto l139
					}
					position++
					if buffer[position] != rune('s') {
						goto l139
					}
					position++
					goto l138
				l139:
					position, tokenIndex = position138, tokenIndex138
					if buffer[position] != rune('v') {
						goto l140
					}
					position++
					if buffer[position] != rune('i') {
						goto l140
					}
					position++
					if buffer[position] != rune('r') {
						goto l140
					}
					position++
					if buffer[position] != rune('o') {
						goto l140
					}
					position++
					if buffer[position] != rune('i') {
						goto l140
					}
					position++
					if buffer[position] != rune('d') {
						goto l140
					}
					position++
					if buffer[position] != rune('i') {
						goto l140
					}
					position++
					if buffer[position] != rune('c') {
						goto l140
					}
					position++
					if buffer[position] != rune('e') {
						goto l140
					}
					position++
					if buffer[position] != rune('t') {
						goto l140
					}
					position++
					if buffer[position] != rune('e') {
						goto l140
					}
					position++
					if buffer[position] != rune('s') {
						goto l140
					}
					position++
					goto l138
				l140:
					position, tokenIndex = position138, tokenIndex138
					if buffer[position] != rune('s') {
						goto l141
					}
					position++
					if buffer[position] != rune('a') {
						goto l141
					}
					position++
					if buffer[position] != rune('t') {
						goto l141
					}
					position++
					if buffer[position] != rune('e') {
						goto l141
					}
					position++
					if buffer[position] != rune('l') {
						goto l141
					}
					position++
					if buffer[position] != rune('l') {
						goto l141
					}
					position++
					if buffer[position] != rune('i') {
						goto l141
					}
					position++
					if buffer[position] != rune('t') {
						goto l141
					}
					position++
					if buffer[position] != rune('i') {
						goto l141
					}
					position++
					if buffer[position] != rune('c') {
						goto l141
					}
					position++
					if buffer[position] != rune('e') {
						goto l141
					}
					position++
					if buffer[position] != rune('t') {
						goto l141
					}
					position++
					if buffer[position] != rune('e') {
						goto l141
					}
					position++
					if buffer[position] != rune('s') {
						goto l141
					}
					position++
					goto l138
				l141:
					position, tokenIndex = position138, tokenIndex138
					if buffer[position] != rune('v') {
						goto l136
					}
					position++
					if buffer[position] != rune('i') {
						goto l136
					}
					position++
					if buffer[position] != rune('r') {
						goto l136
					}
					position++
					if buffer[position] != rune('i') {
						goto l136
					}
					position++
					if buffer[position] != rune('f') {
						goto l136
					}
					position++
					if buffer[position] != rune('o') {
						goto l136
					}
					position++
					if buffer[position] != rune('r') {
						goto l136
					}
					position++
					if buffer[position] != rune('m') {
						goto l136
					}
					position++
					if buffer[position] != rune('i') {
						goto l136
					}
					position++
					if buffer[position] != rune('c') {
						goto l136
					}
					position++
					if buffer[position] != rune('e') {
						goto l136
					}
					position++
					if buffer[position] != rune('t') {
						goto l136
					}
					position++
					if buffer[position] != rune('e') {
						goto l136
					}
					position++
					if buffer[position] != rune('s') {
						goto l136
					}
					position++
				}
			l138:
				{
					position142, tokenIndex142 := position, tokenIndex
					if !_rules[ruleLetter]() {
						goto l142
					}
					goto l136
				l142:
					position, tokenIndex = position142, tokenIndex142
				}
				add(ruleClassSuffix, position137)
			}
			return true
		l136:
			position, tokenIndex = position136, tokenIndex136
			return false
		},
		/* 21 Subphylum <- <(CapsLetter (!SubphylumSuffix Letter)+ SubphylumSuffix)> */
		func() bool {
			position143, tokenIndex143 := position, tokenIndex
			{
				position144 := position
				if !_rules[ruleCapsLetter]() {
					goto l143
				}
				{
					position147, tokenIndex147 := position, tokenIndex
					if !_rules[ruleSubphylumSuffix]() {
						goto l147
					}
					goto l143
				l147:
					position, tokenIndex = position147, tokenIndex147
				}
				if !_rules[ruleLetter]() {
					goto l143
				}
			l145:
				{
					position146, tokenIndex146 := position, tokenIndex
					{
						position148, tokenIndex148 := position, tokenIndex
						if !_rules[ruleSubphylumSuffix]() {
							goto l148
						}
						goto l146
					l148:
						position, tokenIndex = position148, tokenIndex148
					}
					if !_rules[ruleLetter]() {
						goto l146
					}
					goto l145
				l146:
					position, tokenIndex = position146, tokenIndex146
				}
				if !_rules[ruleSubphylumSuffix]() {
					goto l143
				}
				add(ruleSubphylum, position144)
			}
			return true
		l143:
			position, tokenIndex = position143, tokenIndex143
			return false
		},
		/* 22 SubphylumSuffix <- <((('v' 'i' 'r' 'i' 'c' 'o' 't' 'i' 'n' 'a') / ('v' 'i' 'r' 'o' 'i' 'd' 'i' 'c' 'o' 't' 'i' 'n' 'a') / ('s' 'a' 't' 'e' 'l' 'l' 'i' 't' 'i' 'c' 'o' 't' 'i' 'n' 'a') / ('v' 'i' 'r' 'i' 'f' 'o' 'r' 'm' 'i' 'c' 'o' 't' 'i' 'n' 'a')) !Letter)> */
		func() bool {
			position149, tokenIndex149 := position, tokenIndex
			{
				position150 := position
				{
					position151, tokenIndex151 := position, tokenIndex
					if buffer[position] != rune('v') {
						goto l152
					}
					position++
					if buffer[position] != rune('i') {
						goto l152
					}
					position++
					if buffer[position] != rune('r') {
						goto l152
					}
					position++
					if buffer[position] != rune('i') {
						goto l152
					}
					position++
					if buffer[position] != rune('c') {
						goto l152
					}
					position++
					if buffer[position] != rune('o') {
						goto l152
					}
					position++
					if buffer[position] != rune('t') {
						goto l152
					}
					position++
					if buffer[position] != rune('i') {
						goto l152
					}
					position++
					if buffer[position] != rune('n') {
						goto l152
					}
					position++
					if buffer[position] != rune('a') {
						goto l152
					}
					position++
					goto l151
				l152:
					position, tokenIndex = position151, tokenIndex151
					if buffer[position] != rune('v') {
						goto l153
					}
					position++
					if buffer[position] != rune('i') {
						goto l153
					}
					position++
					if buffer[position] != rune('r') {
						goto l153
					}
					position++
					if buffer[position] != rune('o') {
						goto l153
					}
					position++
					if buffer[position] != rune('i') {
						goto l153
					}
					position++
					if buffer[position] != rune('d') {
						goto l153
					}
					position++
					if buffer[position] != rune('i') {
						goto l153
					}
					position++
					if buffer[position] != rune('c') {
						goto l153
					}
					position++
					if buffer[position] != rune('o') {
						goto l153
					}
					position++
					if buffer[position] != rune('t') {
						goto l153
					}
					position++
					if buffer[position] != rune('i') {
						goto l153
					}
					position++
					if buffer[position] != rune('n') {
						goto l153
					}
					position++
					if buffer[position] != rune('a') {
						goto l153
					}
					position++
					goto l151
				l153:
					position, tokenIndex = position151, tokenIndex151
					if buffer[position] != rune('s') {
						goto l154
					}
					position++
					if buffer[position] != rune('a') {
						goto l154
					}
					position++
					if buffer[position] != rune('t') {
						goto l154
					}
					position++
					if buffer[position] != rune('e') {
						goto l154
					}
					position++
					if buffer[position] != rune('l') {
						goto l154
					}
					position++
					if buffer[position] != rune('l') {
						goto l154
					}
					position++
					if buffer[position] != rune('i') {
						goto l154
					}
					position++
					if buffer[position] != rune('t') {
						goto l154
					}
					position++
					if buffer[position] != rune('i') {
						goto l154
					}
					position++
					if buffer[position] != rune('c') {
						goto l154
					}
					position++
					if buffer[position] != rune('o') {
						goto l154
					}
					position++
					if buffer[position] != rune('t') {
						goto l154
					}
					position++
					if buffer[position] != rune('i') {
						goto l154
					}
					position++
					if buffer[position] != rune('n') {
						goto l154
					}
					position++
					if buffer[position] != rune('a') {
						goto l154
					}
					position++
					goto l151
				l154:
					position, tokenIndex = position151, tokenIndex151
					if buffer[position] != rune('v') {
						goto l149
					}
					position++
					if buffer[position] != rune('i') {
						goto l149
					}
					position++
					if buffer[position] != rune('r') {
						goto l149
					}
					position++
					if buffer[position] != rune('i') {
						goto l149
					}
					position++
					if buffer[position] != rune('f') {
						goto l149
					}
					position++
					if buffer[position] != rune('o') {
						goto l149
					}
					position++
					if buffer[position] != rune('r') {
						goto l149
					}
					position++
					if buffer[position] != rune('m') {
						goto l149
					}
					position++
					if buffer[position] != rune('i') {
						goto l149
					}
					position++
					if buffer[position] != rune('c') {
						goto l149
					}
					position++
					if buffer[position] != rune('o') {
						goto l149
					}
					position++
					if buffer[position] != rune('t') {
						goto l149
					}
					position++
					if buffer[position] != rune('i') {
						goto l149
					}
					position++
					if buffer[position] != rune('n') {
						goto l149
					}
					position++
					if buffer[position] != rune('a') {
						goto l149
					}
					position++
				}
			l151:
				{
					position155, tokenIndex155 := position, tokenIndex
					if !_rules[ruleLetter]() {
						goto l155
					}
					goto l149
				l155:
					position, tokenIndex = position155, tokenIndex155
				}
				add(ruleSubphylumSuffix, position150)
			}
			return true
		l149:
			position, tokenIndex = position149, tokenIndex149
			return false
		},
		/* 23 Phylum <- <(CapsLetter (!PhylumSuffix Letter)+ PhylumSuffix)> */
		func() bool {
			position156, tokenIndex156 := position, tokenIndex
			{
				position157 := position
				if !_rules[ruleCapsLetter]() {
					goto l156
				}
				{
					position160, tokenIndex160 := position, tokenIndex
					if !_rules[rulePhylumSuffix]() {
						goto l160
					}
					goto l156
				l160:
					position, tokenIndex = position160, tokenIndex160
				}
				if !_rules[ruleLetter]() {
					goto l156
				}
			l158:
				{
					position159, tokenIndex159 := position, tokenIndex
					{
						position161, tokenIndex161 := position, tokenIndex
						if !_rules[rulePhylumSuffix]() {
							goto l161
						}
						goto l159
					l161:
						position, tokenIndex = position161, tokenIndex161
					}
					if !_rules[ruleLetter]() {
						goto l159
					}
					goto l158
				l159:
					position, tokenIndex = position159, tokenIndex159
				}
				if !_rules[rulePhylumSuffix]() {
					goto l156
				}
				add(rulePhylum, position157)
			}
			return true
		l156:
			position, tokenIndex = position156, tokenIndex156
			return false
		},
		/* 24 PhylumSuffix <- <((('v' 'i' 'r' 'i' 'c' 'o' 't' 'a') / ('v' 'i' 'r' 'o' 'i' 'd' 'i' 'c' 'o' 't' 'a') / ('s' 'a' 't' 'e' 'l' 'l' 'i' 't' 'i' 'c' 'o' 't' 'a') / ('v' 'i' 'r' 'i' 'f' 'o' 'r' 'm' 'i' 'c' 'o' 't' 'a')) !Letter)> */
		func() bool {
			position162, tokenIndex162 := position, tokenIndex
			{
				position163 := position
				{
					position164, tokenIndex164 := position, tokenIndex
					if buffer[position] != rune('v') {
						goto l165
					}
					position++
					if buffer[position] != rune('i') {
						goto l165
					}
					position++
					if buffer[position] != rune('r') {
						goto l165
					}
					position++
					if buffer[position] != rune('i') {
						goto l165
					}
					position++
					if buffer[position] != rune('c') {
						goto l165
					}
					position++
					if buffer[position] != rune('o') {
						goto l165
					}
					position++
					if buffer[position] != rune('t') {
						goto l165
					}
					position++
					if buffer[position] != rune('a') {
						goto l165
					}
					position++
					goto l164
				l165:
					position, tokenIndex = position164, tokenIndex164
					if buffer[position] != rune('v') {
						goto l166
					}
					position++
					if buffer[position] != rune('i') {
						goto l166
					}
					position++
					if buffer[position] != rune('r') {
						goto l166
					}
					position++
					if buffer[position] != rune('o') {
						goto l166
					}
					position++
					if buffer[position] != rune('i') {
						goto l166
					}
					position++
					if buffer[position] != rune('d') {
						goto l166
					}
					position++
					if buffer[position] != rune('i') {
						goto l166
					}
					position++
					if buffer[position] != rune('c') {
						goto l166
					}
					position++
					if buffer[position] != rune('o') {
						goto l166
					}
					position++
					if buffer[position] != rune('t') {
						goto l166
					}
					position++
					if buffer[position] != rune('a') {
						goto l166
					}
					position++
					goto l164
				l166:
					position, tokenIndex = position164, tokenIndex164
					if buffer[position] != rune('s') {
						goto l167
					}
					position++
					if buffer[position] != rune('a') {
						goto l167
					}
					position++
					if buffer[position] != rune('t') {
						goto l167
					}
					position++
					if buffer[position] != rune('e') {
						goto l167
					}
					position++
					if buffer[position] != rune('l') {
						goto l167
					}
					position++
					if buffer[position] != rune('l') {
						goto l167
					}
					position++
					if buffer[position] != rune('i') {
						goto l167
					}
					position++
					if buffer[position] != rune('t') {
						goto l167
					}
					position++
					if buffer[position] != rune('i') {
						goto l167
					}
					position++
					if buffer[position] != rune('c') {
						goto l167
					}
					position++
					if buffer[position] != rune('o') {
						goto l167
					}
					position++
					if buffer[position] != rune('t') {
						goto l167
					}
					position++
					if buffer[position] != rune('a') {
						goto l167
					}
					position++
					goto l164
				l167:
					position, tokenIndex = position164, tokenIndex164
					if buffer[position] != rune('v') {
						goto l162
					}
					position++
					if buffer[position] != rune('i') {
						goto l162
					}
					position++
					if buffer[position] != rune('r') {
						goto l162
					}
					position++
					if buffer[position] != rune('i') {
						goto l162
					}
					position++
					if buffer[position] != rune('f') {
						goto l162
					}
					position++
					if buffer[position] != rune('o') {
						goto l162
					}
					position++
					if buffer[position] != rune('r') {
						goto l162
					}
					position++
					if buffer[position] != rune('m') {
						goto l162
					}
					position++
					if buffer[position] != rune('i') {
						goto l162
					}
					position++
					if buffer[position] != rune('c') {
						goto l162
					}
					position++
					if buffer[position] != rune('o') {
						goto l162
					}
					position++
					if buffer[position] != rune('t') {
						goto l162
					}
					position++
					if buffer[position] != rune('a') {
						goto l162
					}
					position++
				}
			l164:
				{
					position168, tokenIndex168 := position, tokenIndex
					if !_rules[ruleLetter]() {
						goto l168
					}
					goto l162
				l168:
					position, tokenIndex = position168, tokenIndex168
				}
				add(rulePhylumSuffix, position163)
			}
			return true
		l162:
			position, tokenIndex = position162, tokenIndex162
			return false
		},
		/* 25 Subkingdom <- <(CapsLetter (!SubkingdomSuffix Letter)+ SubkingdomSuffix)> */
		func() bool {
			position169, tokenIndex169 := position, tokenIndex
			{
				position170 := position
				if !_rules[ruleCapsLetter]() {
					goto l169
				}
				{
					position173, tokenIndex173 := position, tokenIndex
					if !_rules[ruleSubkingdomSuffix]() {
						goto l173
					}
					goto l169
				l173:
					position, tokenIndex = position173, tokenIndex173
				}
				if !_rules[ruleLetter]() {
					goto l169
				}
			l171:
				{
					position172, tokenIndex172 := position, tokenIndex
					{
						position174, tokenIndex174 := position, tokenIndex
						if !_rules[ruleSubkingdomSuffix]() {
							goto l174
						}
						goto l172
					l174:
						position, tokenIndex = position174, tokenIndex174
					}
					if !_rules[ruleLetter]() {
						goto l172
					}
					goto l171
				l172:
					position, tokenIndex = position172, tokenIndex172
				}
				if !_rules[ruleSubkingdomSuffix]() {
					goto l169
				}
				add(ruleSubkingdom, position170)
			}
			return true
		l169:
			position, tokenIndex = position169, tokenIndex169
			return false
		},
		/* 26 SubkingdomSuffix <- <((('v' 'i' 'r' 'i' 't' 'e' 's') / ('v' 'i' 'r' 'o' 'i' 'd' 'i' 't' 'e' 's') / ('s' 'a' 't' 'e' 'l' 'l' 'i' 't' 'i' 't' 'e' 's') / ('v' 'i' 'r' 'i' 'f' 'o' 'r' 'm' 'i' 't' 'e' 's')) !Letter)> */
		func() bool {
			position175, tokenIndex175 := position, tokenIndex
			{
				position176 := position
				{
					position177, tokenIndex177 := position, tokenIndex
					if buffer[position] != rune('v') {
						goto l178
					}
					position++
					if buffer[position] != rune('i') {
						goto l178
					}
					position++
					if buffer[position] != rune('r') {
						goto l178
					}
					position++
					if buffer[position] != rune('i') {
						goto l178
					}
					position++
					if buffer[position] != rune('t') {
						goto l178
					}
					position++
					if buffer[position] != rune('e') {
						goto l178
					}
					position++
					if buffer[position] != rune('s') {
						goto l178
					}
					position++
					goto l177
				l178:
					position, tokenIndex = position177, tokenIndex177
					if buffer[position] != rune('v') {
						goto l179
					}
					position++
					if buffer[position] != rune('i') {
						goto l179
					}
					position++
					if buffer[position] != rune('r') {
						goto l179
					}
					position++
					if buffer[position] != rune('o') {
						goto l179
					}
					position++
					if buffer[position] != rune('i') {
						goto l179
					}
					position++
					if buffer[position] != rune('d') {
						goto l179
					}
					position++
					if buffer[position] != rune('i') {
						goto l179
					}
					position++
					if buffer[position] != rune('t') {
						goto l179
					}
					position++
					if buffer[position] != rune('e') {
						goto l179
					}
					position++
					if buffer[position] != rune('s') {
						goto l179
					}
					position++
					goto l177
				l179:
					position, tokenIndex = position177, tokenIndex177
					if buffer[position] != rune('s') {
						goto l180
					}
					position++
					if buffer[position] != rune('a') {
						goto l180
					}
					position++
					if buffer[position] != rune('t') {
						goto l180
					}
					position++
					if buffer[position] != rune('e') {
						goto l180
					}
					position++
					if buffer[position] != rune('l') {
						goto l180
					}
					position++
					if buffer[position] != rune('l') {
						goto l180
					}
					position++
					if buffer[position] != rune('i') {
						goto l180
					}
					position++
					if buffer[position] != rune('t') {
						goto l180
					}
					position++
					if buffer[position] != rune('i') {
						goto l180
					}
					position++
					if buffer[position] != rune('t') {
						goto l180
					}
					position++
					if buffer[position] != rune('e') {
						goto l180
					}
					position++
					if buffer[position] != rune('s') {
						goto l180
					}
					position++
					goto l177
				l180:
					position, tokenIndex = position177, tokenIndex177
					if buffer[position] != rune('v') {
						goto l175
					}
					position++
					if buffer[position] != rune('i') {
						goto l175
					}
					position++
					if buffer[position] != rune('r') {
						goto l175
					}
					position++
					if buffer[position] != rune('i') {
						goto l175
					}
					position++
					if buffer[position] != rune('f') {
						goto l175
					}
					position++
					if buffer[position] != rune('o') {
						goto l175
					}
					position++
					if buffer[position] != rune('r') {
						goto l175
					}
					position++
					if buffer[position] != rune('m') {
						goto l175
					}
					position++
					if buffer[position] != rune('i') {
						goto l175
					}
					position++
					if buffer[position] != rune('t') {
						goto l175
					}
					position++
					if buffer[position] != rune('e') {
						goto l175
					}
					position++
					if buffer[position] != rune('s') {
						goto l175
					}
					position++
				}
			l177:
				{
					position181, tokenIndex181 := position, tokenIndex
					if !_rules[ruleLetter]() {
						goto l181
					}
					goto l175
				l181:
					position, tokenIndex = position181, tokenIndex181
				}
				add(ruleSubkingdomSuffix, position176)
			}
			return true
		l175:
			position, tokenIndex = position175, tokenIndex175
			return false
		},
		/* 27 Kingdom <- <(CapsLetter (!KingdomSuffix Letter)+ KingdomSuffix)> */
		func() bool {
			position182, tokenIndex182 := position, tokenIndex
			{
				position183 := position
				if !_rules[ruleCapsLetter]() {
					goto l182
				}
				{
					position186, tokenIndex186 := position, tokenIndex
					if !_rules[ruleKingdomSuffix]() {
						goto l186
					}
					goto l182
				l186:
					position, tokenIndex = position186, tokenIndex186
				}
				if !_rules[ruleLetter]() {
					goto l182
				}
			l184:
				{
					position185, tokenIndex185 := position, tokenIndex
					{
						position187, tokenIndex187 := position, tokenIndex
						if !_rules[ruleKingdomSuffix]() {
							goto l187
						}
						goto l185
					l187:
						position, tokenIndex = position187, tokenIndex187
					}
					if !_rules[ruleLetter]() {
						goto l185
					}
					goto l184
				l185:
					position, tokenIndex = position185, tokenIndex185
				}
				if !_rules[ruleKingdomSuffix]() {
					goto l182
				}
				add(ruleKingdom, position183)
			}
			return true
		l182:
			position, tokenIndex = position182, tokenIndex182
			return false
		},
		/* 28 KingdomSuffix <- <((('v' 'i' 'r' 'a' 'e') / ('v' 'i' 'r' 'o' 'i' 'd' 'a' 'e') / ('s' 'a' 't' 'e' 'l' 'l' 'i' 't' 'a' 'e') / ('v' 'i' 'r' 'i' 'f' 'o' 'r' 'm' 'a' 'e')) !Letter)> */
		func() bool {
			position188, tokenIndex188 := position, tokenIndex
			{
				position189 := position
				{
					position190, tokenIndex190 := position, tokenIndex
					if buffer[position] != rune('v') {
						goto l191
					}
					position++
					if buffer[position] != rune('i') {
						goto l191
					}
					position++
					if buffer[position] != rune('r') {
						goto l191
					}
					position++
					if buffer[position] != rune('a') {
						goto l191
					}
					position++
					if buffer[position] != rune('e') {
						goto l191
					}
					position++
					goto l190
				l191:
					position, tokenIndex = position190, tokenIndex190
					if buffer[position] != rune('v') {
						goto l192
					}
					position++
					if buffer[position] != rune('i') {
						goto l192
					}
					position++
					if buffer[position] != rune('r') {
						goto l192
					}
					position++
					if buffer[position] != rune('o') {
						goto l192
					}
					position++
					if buffer[position] != rune('i') {
						goto l192
					}
					position++
					if buffer[position] != rune('d') {
						goto l192
					}
					position++
					if buffer[position] != rune('a') {
						goto l192
					}
					position++
					if buffer[position] != rune('e') {
						goto l192
					}
					position++
					goto l190
				l192:
					position, tokenIndex = position190, tokenIndex190
					if buffer[position] != rune('s') {
						goto l193
					}
					position++
					if buffer[position] != rune('a') {
						goto l193
					}
					position++
					if buffer[position] != rune('t') {
						goto l193
					}
					position++
					if buffer[position] != rune('e') {
						goto l193
					}
					position++
					if buffer[position] != rune('l') {
						goto l193
					}
					position++
					if buffer[position] != rune('l') {
						goto l193
					}
					position++
					if buffer[position] != rune('i') {
						goto l193
					}
					position++
					if buffer[position] != rune('t') {
						goto l193
					}
					position++
					if buffer[position] != rune('a') {
						goto l193
					}
					position++
					if buffer[position] != rune('e') {
						goto l193
					}
					position++
					goto l190
				l193:
					position, tokenIndex = position190, tokenIndex190
					if buffer[position] != rune('v') {
						goto l188
					}
					position++
					if buffer[position] != rune('i') {
						goto l188
					}
					position++
					if buffer[position] != rune('r') {
						goto l188
					}
					position++
					if buffer[position] != rune('i') {
						goto l188
					}
					position++
					if buffer[position] != rune('f') {
						goto l188
					}
					position++
					if buffer[position] != rune('o') {
						goto l188
					}
					position++
					if buffer[position] != rune('r') {
						goto l188
					}
					position++
					if buffer[position] != rune('m') {
						goto l188
					}
					position++
					if buffer[position] != rune('a') {
						goto l188
					}
					position++
					if buffer[position] != rune('e') {
						goto l188
					}
					position++
				}
			l190:
				{
					position194, tokenIndex194 := position, tokenIndex
					if !_rules[ruleLetter]() {
						goto l194
					}
					goto l188
				l194:
					position, tokenIndex = position194, tokenIndex194
				}
				add(ruleKingdomSuffix, position189)
			}
			return true
		l188:
			position, tokenIndex = position188, tokenIndex188
			return false
		},
		/* 29 Subrealm <- <(CapsLetter (!SubrealmSuffix Letter)+ SubrealmSuffix)> */
		func() bool {
			position195, tokenIndex195 := position, tokenIndex
			{
				position196 := position
				if !_rules[ruleCapsLetter]() {
					goto l195
				}
				{
					position199, tokenIndex199 := position, tokenIndex
					if !_rules[ruleSubrealmSuffix]() {
						goto l199
					}
					goto l195
				l199:
					position, tokenIndex = position199, tokenIndex199
				}
				if !_rules[ruleLetter]() {
					goto l195
				}
			l197:
				{
					position198, tokenIndex198 := position, tokenIndex
					{
						position200, tokenIndex200 := position, tokenIndex
						if !_rules[ruleSubrealmSuffix]() {
							goto l200
						}
						goto l198
					l200:
						position, tokenIndex = position200, tokenIndex200
					}
					if !_rules[ruleLetter]() {
						goto l198
					}
					goto l197
				l198:
					position, tokenIndex = position198, tokenIndex198
				}
				if !_rules[ruleSubrealmSuffix]() {
					goto l195
				}
				add(ruleSubrealm, position196)
			}
			return true
		l195:
			position, tokenIndex = position195, tokenIndex195
			return false
		},
		/* 30 SubrealmSuffix <- <((('v' 'i' 'r' 'a') / ('v' 'i' 'r' 'o' 'i' 'd' 'a') / ('s' 'a' 't' 'e' 'l' 'l' 'i' 't' 'a') / ('v' 'i' 'r' 'i' 'f' 'o' 'r' 'm' 'a')) !Letter)> */
		func() bool {
			position201, tokenIndex201 := position, tokenIndex
			{
				position202 := position
				{
					position203, tokenIndex203 := position, tokenIndex
					if buffer[position] != rune('v') {
						goto l204
					}
					position++
					if buffer[position] != rune('i') {
						goto l204
					}
					position++
					if buffer[position] != rune('r') {
						goto l204
					}
					position++
					if buffer[position] != rune('a') {
						goto l204
					}
					position++
					goto l203
				l204:
					position, tokenIndex = position203, tokenIndex203
					if buffer[position] != rune('v') {
						goto l205
					}
					position++
					if buffer[position] != rune('i') {
						goto l205
					}
					position++
					if buffer[position] != rune('r') {
						goto l205
					}
					position++
					if buffer[position] != rune('o') {
						goto l205
					}
					position++
					if buffer[position] != rune('i') {
						goto l205
					}
					position++
					if buffer[position] != rune('d') {
						goto l205
					}
					position++
					if buffer[position] != rune('a') {
						goto l205
					}
					position++
					goto l203
				l205:
					position, tokenIndex = position203, tokenIndex203
					if buffer[position] != rune('s') {
						goto l206
					}
					position++
					if buffer[position] != rune('a') {
						goto l206
					}
					position++
					if buffer[position] != rune('t') {
						goto l206
					}
					position++
					if buffer[position] != rune('e') {
						goto l206
					}
					position++
					if buffer[position] != rune('l') {
						goto l206
					}
					position++
					if buffer[position] != rune('l') {
						goto l206
					}
					position++
					if buffer[position] != rune('i') {
						goto l206
					}
					position++
					if buffer[position] != rune('t') {
						goto l206
					}
					position++
					if buffer[position] != rune('a') {
						goto l206
					}
					position++
					goto l203
				l206:
					position, tokenIndex = position203, tokenIndex203
					if buffer[position] != rune('v') {
						goto l201
					}
					position++
					if buffer[position] != rune('i') {
						goto l201
					}
					position++
					if buffer[position] != rune('r') {
						goto l201
					}
					position++
					if buffer[position] != rune('i') {
						goto l201
					}
					position++
					if buffer[position] != rune('f') {
						goto l201
					}
					position++
					if buffer[position] != rune('o') {
						goto l201
					}
					position++
					if buffer[position] != rune('r') {
						goto l201
					}
					position++
					if buffer[position] != rune('m') {
						goto l201
					}
					position++
					if buffer[position] != rune('a') {
						goto l201
					}
					position++
				}
			l203:
				{
					position207, tokenIndex207 := position, tokenIndex
					if !_rules[ruleLetter]() {
						goto l207
					}
					goto l201
				l207:
					position, tokenIndex = position207, tokenIndex207
				}
				add(ruleSubrealmSuffix, position202)
			}
			return true
		l201:
			position, tokenIndex = position201, tokenIndex201
			return false
		},
		/* 31 Realm <- <(CapsLetter (!RealmSuffix Letter)+ RealmSuffix)> */
		func() bool {
			position208, tokenIndex208 := position, tokenIndex
			{
				position209 := position
				if !_rules[ruleCapsLetter]() {
					goto l208
				}
				{
					position212, tokenIndex212 := position, tokenIndex
					if !_rules[ruleRealmSuffix]() {
						goto l212
					}
					goto l208
				l212:
					position, tokenIndex = position212, tokenIndex212
				}
				if !_rules[ruleLetter]() {
					goto l208
				}
			l210:
				{
					position211, tokenIndex211 := position, tokenIndex
					{
						position213, tokenIndex213 := position, tokenIndex
						if !_rules[ruleRealmSuffix]() {
							goto l213
						}
						goto l211
					l213:
						position, tokenIndex = position213, tokenIndex213
					}
					if !_rules[ruleLetter]() {
						goto l211
					}
					goto l210
				l211:
					position, tokenIndex = position211, tokenIndex211
				}
				if !_rules[ruleRealmSuffix]() {
					goto l208
				}
				add(ruleRealm, position209)
			}
			return true
		l208:
			position, tokenIndex = position208, tokenIndex208
			return false
		},
		/* 32 RealmSuffix <- <((('v' 'i' 'r' 'i' 'a') / ('v' 'i' 'r' 'o' 'i' 'd' 'i' 'a') / ('s' 'a' 't' 'e' 'l' 'l' 'i' 't' 'i' 'a') / ('v' 'i' 'r' 'i' 'f' 'o' 'r' 'm' 'i' 'a')) !Letter)> */
		func() bool {
			position214, tokenIndex214 := position, tokenIndex
			{
				position215 := position
				{
					position216, tokenIndex216 := position, tokenIndex
					if buffer[position] != rune('v') {
						goto l217
					}
					position++
					if buffer[position] != rune('i') {
						goto l217
					}
					position++
					if buffer[position] != rune('r') {
						goto l217
					}
					position++
					if buffer[position] != rune('i') {
						goto l217
					}
					position++
					if buffer[position] != rune('a') {
						goto l217
					}
					position++
					goto l216
				l217:
					position, tokenIndex = position216, tokenIndex216
					if buffer[position] != rune('v') {
						goto l218
					}
					position++
					if buffer[position] != rune('i') {
						goto l218
					}
					position++
					if buffer[position] != rune('r') {
						goto l218
					}
					position++
					if buffer[position] != rune('o') {
						goto l218
					}
					position++
					if buffer[position] != rune('i') {
						goto l218
					}
					position++
					if buffer[position] != rune('d') {
						goto l218
					}
					position++
					if buffer[position] != rune('i') {
						goto l218
					}
					position++
					if buffer[position] != rune('a') {
						goto l218
					}
					position++
					goto l216
				l218:
					position, tokenIndex = position216, tokenIndex216
					if buffer[position] != rune('s') {
						goto l219
					}
					position++
					if buffer[position] != rune('a') {
						goto l219
					}
					position++
					if buffer[position] != rune('t') {
						goto l219
					}
					position++
					if buffer[position] != rune('e') {
						goto l219
					}
					position++
					if buffer[position] != rune('l') {
						goto l219
					}
					position++
					if buffer[position] != rune('l') {
						goto l219
					}
					position++
					if buffer[position] != rune('i') {
						goto l219
					}
					position++
					if buffer[position] != rune('t') {
						goto l219
					}
					position++
					if buffer[position] != rune('i') {
						goto l219
					}
					position++
					if buffer[position] != rune('a') {
						goto l219
					}
					position++
					goto l216
				l219:
					position, tokenIndex = position216, tokenIndex216
					if buffer[position] != rune('v') {
						goto l214
					}
					position++
					if buffer[position] != rune('i') {
						goto l214
					}
					position++
					if buffer[position] != rune('r') {
						goto l214
					}
					position++
					if buffer[position] != rune('i') {
						goto l214
					}
					position++
					if buffer[position] != rune('f') {
						goto l214
					}
					position++
					if buffer[position] != rune('o') {
						goto l214
					}
					position++
					if buffer[position] != rune('r') {
						goto l214
					}
					position++
					if buffer[position] != rune('m') {
						goto l214
					}
					position++
					if buffer[position] != rune('i') {
						goto l214
					}
					position++
					if buffer[position] != rune('a') {
						goto l214
					}
					position++
				}
			l216:
				{
					position220, tokenIndex220 := position, tokenIndex
					if !_rules[ruleLetter]() {
						goto l220
					}
					goto l214
				l220:
					position, tokenIndex = position220, tokenIndex220
				}
				add(ruleRealmSuffix, position215)
			}
			return true
		l214:
			position, tokenIndex = position214, tokenIndex214
			return false
		},
		/* 33 Dash <- <'-'> */
		func() bool {
			position221, tokenIndex221 := position, tokenIndex
			{
				position222 := position
				if buffer[position] != rune('-') {
					goto l221
				}
				position++
				add(ruleDash, position222)
			}
			return true
		l221:
			position, tokenIndex = position221, tokenIndex221
			return false
		},
		/* 34 Num <- <[0-9]> */
		func() bool {
			position223, tokenIndex223 := position, tokenIndex
			{
				position224 := position
				if c := buffer[position]; c < rune('0') || c > rune('9') {
					goto l223
				}
				position++
				add(ruleNum, position224)
			}
			return true
		l223:
			position, tokenIndex = position223, tokenIndex223
			return false
		},
		/* 35 Letter <- <[a-z]> */
		func() bool {
			position225, tokenIndex225 := position, tokenIndex
			{
				position226 := position
				if c := buffer[position]; c < rune('a') || c > rune('z') {
					goto l225
				}
				position++
				add(ruleLetter, position226)
			}
			return true
		l225:
			position, tokenIndex = position225, tokenIndex225
			return false
		},
		/* 36 CapsLetter <- <[A-Z]> */
		func() bool {
			position227, tokenIndex227 := position, tokenIndex
			{
				position228 := position
				if c := buffer[position]; c < rune('A') || c > rune('Z') {
					goto l227
				}
				position++
				add(ruleCapsLetter, position228)
			}
			return true
		l227:
			position, tokenIndex = position227, tokenIndex227
			return false
		},
		/* 37 _ <- <SingleSpace+> */
		func() bool {
			position229, tokenIndex229 := position, tokenIndex
			{
				position230 := position
				if !_rules[ruleSingleSpace]() {
					goto l229
				}
			l231:
				{
					position232, tokenIndex232 := position, tokenIndex
					if !_rules[ruleSingleSpace]() {
						goto l232
					}
					goto l231
				l232:
					position, tokenIndex = position232, tokenIndex232
				}
				add(rule_, position230)
			}
			return true
		l229:
			position, tokenIndex = position229, tokenIndex229
			return false
		},
		/* 38 SingleSpace <- <(' ' / OtherSpace)> */
		func() bool {
			position233, tokenIndex233 := position, tokenIndex
			{
				position234 := position
				{
					position235, tokenIndex235 := position, tokenIndex
					if buffer[position] != rune(' ') {
						goto l236
					}
					position++
					goto l235
				l236:
					position, tokenIndex = position235, tokenIndex235
					if !_rules[ruleOtherSpace]() {
						goto l233
					}
				}
			l235:
				add(ruleSingleSpace, position234)
			}
			return true
		l233:
			position, tokenIndex = position233, tokenIndex233
			return false
		},
		/* 39 OtherSpace <- <('\u3000' / '\u00a0' / '\t' / '\r' / '\n' / '\f' / '\v')> */
		func() bool {
			position237, tokenIndex237 := position, tokenIndex
			{
				position238 := position
				{
					position239, tokenIndex239 := position, tokenIndex
					if buffer[position] != rune('\u3000') {
						goto l240
					}
					position++
					goto l239
				l240:
					position, tokenIndex = position239, tokenIndex239
					if buffer[position] != rune('\u00a0') {
						goto l241
					}
					position++
					goto l239
				l241:
					position, tokenIndex = position239, tokenIndex239
					if buffer[position] != rune('\t') {
						goto l242
					}
					position++
					goto l239
				l242:
					position, tokenIndex = position239, tokenIndex239
					if buffer[position] != rune('\r') {
						goto l243
					}
					position++
					goto l239
				l243:
					position, tokenIndex = position239, tokenIndex239
					if buffer[position] != rune('\n') {
						goto l244
					}
					position++
					goto l239
				l244:
					position, tokenIndex = position239, tokenIndex239
					if buffer[position] != rune('\f') {
						goto l245
					}
					position++
					goto l239
				l245:
					position, tokenIndex = position239, tokenIndex239
					if buffer[position] != rune('\v') {
						goto l237
					}
					position++
				}
			l239:
				add(ruleOtherSpace, position238)
			}
			return true
		l237:
			position, tokenIndex = position237, tokenIndex237
			return false
		},
		/* 40 END <- <!.> */
		func() bool {
			position246, tokenIndex246 := position, tokenIndex
			{
				position247 := position
				{
					position248, tokenIndex248 := position, tokenIndex
					if !matchDot() {
						goto l248
					}
					goto l246
				l248:
					position, tokenIndex = position248, tokenIndex248
				}
				add(ruleEND, position247)
			}
			return true
		l246:
			position, tokenIndex = position246, tokenIndex246
			return false
		},
	}
	p.rules = _rules
	return nil
}
