name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.22

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
    - run: git fetch --prune --unshallow

    - name: install tools and dependencies
      run: make tools

    - name: Test
      run: make test

    - name: Build
      run: make build

    - name: Build C lib
      run: make clib

    - name: Store C library
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}-clib
        path: binding/lib*
        retention-days: 1
